version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bibliotheque_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build: .
    container_name: bibliotheque_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - mysql


  frontend:
    build:
      context: ./front
    container_name: bibliotheque_frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend

volumes:
  mysql_data: