# ====================================
# = DATA SOURCE
# ====================================

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# ====================================
# = JPA / HIBERNATEE
# ====================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
